spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:mongodb://127.0.0.1:27017/BBDDNoSQL}
      auto-index-creation: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  docker:
    compose:
      lifecycle-management: start-only
springdoc:
  pathsToMatch: /api/**
